/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  PaySlip as PrismaPaySlip,
  PayrollRecord as PrismaPayrollRecord,
} from "@prisma/client";

export class PaySlipServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.PaySlipCountArgs, "select">): Promise<number> {
    return this.prisma.paySlip.count(args);
  }

  async paySlips(args: Prisma.PaySlipFindManyArgs): Promise<PrismaPaySlip[]> {
    return this.prisma.paySlip.findMany(args);
  }
  async paySlip(
    args: Prisma.PaySlipFindUniqueArgs
  ): Promise<PrismaPaySlip | null> {
    return this.prisma.paySlip.findUnique(args);
  }
  async createPaySlip(args: Prisma.PaySlipCreateArgs): Promise<PrismaPaySlip> {
    return this.prisma.paySlip.create(args);
  }
  async updatePaySlip(args: Prisma.PaySlipUpdateArgs): Promise<PrismaPaySlip> {
    return this.prisma.paySlip.update(args);
  }
  async deletePaySlip(args: Prisma.PaySlipDeleteArgs): Promise<PrismaPaySlip> {
    return this.prisma.paySlip.delete(args);
  }

  async getPayrollRecord(
    parentId: string
  ): Promise<PrismaPayrollRecord | null> {
    return this.prisma.paySlip
      .findUnique({
        where: { id: parentId },
      })
      .payrollRecord();
  }
}
