/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PaySlip } from "./PaySlip";
import { PaySlipCountArgs } from "./PaySlipCountArgs";
import { PaySlipFindManyArgs } from "./PaySlipFindManyArgs";
import { PaySlipFindUniqueArgs } from "./PaySlipFindUniqueArgs";
import { CreatePaySlipArgs } from "./CreatePaySlipArgs";
import { UpdatePaySlipArgs } from "./UpdatePaySlipArgs";
import { DeletePaySlipArgs } from "./DeletePaySlipArgs";
import { PayrollRecord } from "../../payrollRecord/base/PayrollRecord";
import { PaySlipService } from "../paySlip.service";
@graphql.Resolver(() => PaySlip)
export class PaySlipResolverBase {
  constructor(protected readonly service: PaySlipService) {}

  async _paySlipsMeta(
    @graphql.Args() args: PaySlipCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PaySlip])
  async paySlips(
    @graphql.Args() args: PaySlipFindManyArgs
  ): Promise<PaySlip[]> {
    return this.service.paySlips(args);
  }

  @graphql.Query(() => PaySlip, { nullable: true })
  async paySlip(
    @graphql.Args() args: PaySlipFindUniqueArgs
  ): Promise<PaySlip | null> {
    const result = await this.service.paySlip(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PaySlip)
  async createPaySlip(
    @graphql.Args() args: CreatePaySlipArgs
  ): Promise<PaySlip> {
    return await this.service.createPaySlip({
      ...args,
      data: {
        ...args.data,

        payrollRecord: args.data.payrollRecord
          ? {
              connect: args.data.payrollRecord,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => PaySlip)
  async updatePaySlip(
    @graphql.Args() args: UpdatePaySlipArgs
  ): Promise<PaySlip | null> {
    try {
      return await this.service.updatePaySlip({
        ...args,
        data: {
          ...args.data,

          payrollRecord: args.data.payrollRecord
            ? {
                connect: args.data.payrollRecord,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PaySlip)
  async deletePaySlip(
    @graphql.Args() args: DeletePaySlipArgs
  ): Promise<PaySlip | null> {
    try {
      return await this.service.deletePaySlip(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => PayrollRecord, {
    nullable: true,
    name: "payrollRecord",
  })
  async getPayrollRecord(
    @graphql.Parent() parent: PaySlip
  ): Promise<PayrollRecord | null> {
    const result = await this.service.getPayrollRecord(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
