/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { EmployeeSalary } from "./EmployeeSalary";
import { EmployeeSalaryCountArgs } from "./EmployeeSalaryCountArgs";
import { EmployeeSalaryFindManyArgs } from "./EmployeeSalaryFindManyArgs";
import { EmployeeSalaryFindUniqueArgs } from "./EmployeeSalaryFindUniqueArgs";
import { CreateEmployeeSalaryArgs } from "./CreateEmployeeSalaryArgs";
import { UpdateEmployeeSalaryArgs } from "./UpdateEmployeeSalaryArgs";
import { DeleteEmployeeSalaryArgs } from "./DeleteEmployeeSalaryArgs";
import { PayrollRecordFindManyArgs } from "../../payrollRecord/base/PayrollRecordFindManyArgs";
import { PayrollRecord } from "../../payrollRecord/base/PayrollRecord";
import { EmployeeSalaryService } from "../employeeSalary.service";
@graphql.Resolver(() => EmployeeSalary)
export class EmployeeSalaryResolverBase {
  constructor(protected readonly service: EmployeeSalaryService) {}

  async _employeeSalariesMeta(
    @graphql.Args() args: EmployeeSalaryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [EmployeeSalary])
  async employeeSalaries(
    @graphql.Args() args: EmployeeSalaryFindManyArgs
  ): Promise<EmployeeSalary[]> {
    return this.service.employeeSalaries(args);
  }

  @graphql.Query(() => EmployeeSalary, { nullable: true })
  async employeeSalary(
    @graphql.Args() args: EmployeeSalaryFindUniqueArgs
  ): Promise<EmployeeSalary | null> {
    const result = await this.service.employeeSalary(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => EmployeeSalary)
  async createEmployeeSalary(
    @graphql.Args() args: CreateEmployeeSalaryArgs
  ): Promise<EmployeeSalary> {
    return await this.service.createEmployeeSalary({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => EmployeeSalary)
  async updateEmployeeSalary(
    @graphql.Args() args: UpdateEmployeeSalaryArgs
  ): Promise<EmployeeSalary | null> {
    try {
      return await this.service.updateEmployeeSalary({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => EmployeeSalary)
  async deleteEmployeeSalary(
    @graphql.Args() args: DeleteEmployeeSalaryArgs
  ): Promise<EmployeeSalary | null> {
    try {
      return await this.service.deleteEmployeeSalary(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [PayrollRecord], { name: "payrollRecords" })
  async findPayrollRecords(
    @graphql.Parent() parent: EmployeeSalary,
    @graphql.Args() args: PayrollRecordFindManyArgs
  ): Promise<PayrollRecord[]> {
    const results = await this.service.findPayrollRecords(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
